// This is to be used for the small business owner spotlights on the news page
export const BizOwnerContent = [
    {
        id: 0,
        title: "Business Counseling & Relief Application Assistance ",
        description: "Shirley arrived in the U.S. from Ecuador in 2014 with her family. After settling in the United States, Shirley knew she wanted to make more for herself and sought out the Latin American Association (LAA) to receive support with starting a business. From the start, she has been passionate about sharing her love of baked goods and pastries with her new community. Since September 2020, Shirley has worked with the Latin American Association, one of the spokes in Atlanta’s Community Navigator Pilot Project. However, after registering her business and finalizing her business plan, Shirley’s hopes to start Sweet Toppings ATL came to a stop when COVID-19 hit. The impacts were so detrimental that Shirley returned to Ecuador to live with her family and had to cease her business.  In January, after returning to the United States and working as an assistant manager at IHOP for a year, Shirley connected again with the LAA. She decided to leave IHOP to pursue her business full-time. Despite the risk Shirley knew she was taking, she reminded LAA staff that Sweet Toppings ATL was her dream, and that she “hopes to see her business grow and eventually franchise like IHOP.” After refining her business plan and taking on her first clients, Shirley enrolled in the Community Navigator Pilot Project this quarter. Her navigator provided Shirley with 39 hours of counseling and training on digital marketing, social media for business owners, Google platforms, Serv Safe, and more. In collaboration with the navigators at the IRC in Atlanta, Shirley attended a grant clinic and applied to local and national grant opportunities, totaling $70,000. In just a few months of restarting her business, and with support from her navigator and other resource partners, Shirley is a successful business owner living her dream. She now works full-time from home and can care for her son. She generates $5,000 per month in profit and saw a 36 percent salary increase. In the future, Shirley plans to work with her navigator and open a coffee shop in a nearby neighborhood.",
        image: "https://i.ibb.co/0hX164d/atl-1.jpg",
    },
    {
        id: 1,
        title: "Business Counseling & Market Access",
        description: "Ernest Nteza, a migrant from Uganda, arrived in the U.S. more than five years ago. Inspired by his grandmother, Ernest founded a coffee company in 2018. The company is centered around the values his grandmother upheld, such as appreciating the differences in people, community, and taking care of others. Earnest and Humble, an East African coffee company, strives to cultivate and process its coffee using sustainable practices concerning the environmental impact and people connected to the industry. Ernest joined the IRC's Community Navigator Pilot Program after the Lagos PHX navigator connected with him, and he is so glad that he did. 'The advice and insights I get on how to approach things in my business are incredible. You can doubt yourself and go through highs and lows, so it's always good to have someone to talk to', Nteza said. He is thankful for the CNPP program because it is difficult to find someone that can relate to his business struggles and needs. Since working with his navigator at Lagos PHX, a regional spoke, he has someone to glean advice and counsel. The navigator assisted Ernest to investigate market opportunities and provided counseling on how to pitch his product to retail stores. Because of this, exciting things have happened for the company, and he secured retail locations. Earnest and Humble recently launched at the Phoenix Public Market this quarter at Sky Harbor Airport and will be launching at AJ's Fine Foods on Central and Camelback in Phoenix later this year. He operates Earnest and Humble with the strong belief that all humans are connected, and coffee is the key to forging and strengthening the relationship between people, cultures, and communities. A faith-based business, Ernest wants to speak joy and peace to people experiencing trials and provide comfort. 'We're seeing the humans behind this beverage. It creates opportunities for us to know them, to care about the environment, their livelihood, and what goes into their cup.' Nteza stated. Its mission is to create specialty coffee that tells a story of its origins and the people who worked to provide the product to the consumer. Coffee has its characteristics, notes, and flavors, and he wants people to be able to appreciate that and educate on specialty coffee. Moreover, he wants to put the spotlight on coffee origins coming from Africa and its regions. As part of his business model, Ernest seeks to help coffee farmers achieve a livable wage and strives to build relationships to further the growth of Africa’s coffee production.  Follow Earnest and Humble on Instagram, @earnestandhumbleco.",
  image: "https://i.ibb.co/71kgL7p/phoenix-1.jpg",
    },
    // This is where you can add additional spotlight tiles
    /*
    {
        id: 2,
        title: "Title 3",
        description: "Description to appear in modal",
        image: "https://example.com/image.jpg",
    },
    */
]
