// This is to be used for the individual regional pages, as well as the region cards
// that appear on the regional overview page.

// View the template at the bottom of this page
export const StateData = {
  arizona: {
    name: 'Arizona',
    map: 'https://i.ibb.co/1QNPV9c/icons8-arizona-90.png',
    partners: [
      {
        name: 'Somali American United Council of Arizona',
        image: 'https://i.ibb.co/WkQTvMQ/sauca.png',
        website: 'https://www.somaliunitedcouncil.org',
      },
      {
        name: 'Refugees and Immigrants Community for Empowerment',
        image:
          'https://i.ibb.co/wYKX0hD/Refugees-and-Immigrants-Community-for-Empowerment-RICE-Logo-Arizona.png',
        website: 'https://www.riceaz.org/',
      },
      {
        name: 'LagosPHX',
        image: 'https://i.ibb.co/rygL7TD/Lagos-PHX-Arizona.png',
        website: 'https://www.instagram.com/lagosphx/',
      },
    ],
    body: 'IRC CNPP will support the small business communities in Metro Phoenix and the surrounding area by providing information and tools to help stabilize and grow local small businesses, including individualized counseling, mentoring, and training.  Business advisors can also help small business owners apply for small business relief grants and loans and assist small business owners who have already received COVID-19 relief loans prepare documentation in support of loan forgiveness. This includes the current City of Phoenix Business Relief grant program. Project partners offer specialized supports to small agricultural and related businesses.  Interpretation services for all services and trainings are available upon request.',
    events: [
         {
        title: 'Profit Soup Pt 1-Measure, Understand, Get it Done!',
        date: 'April 10',
        time: '10:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://www.maricopa-sbdc.com/event/profit-soup-pt-1-measure-understand-get-it-done/',
      },
               {
        title: 'Profit Soup Pt 2-Financial Statements: Where the Story of your Business is Told',
        date: 'April 24',
        time: '10:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://www.maricopa-sbdc.com/event/profit-soup-pt-2-financial-statements-where-the-story-of-your-business-is-told/',
      },
    ],
    upcoming: {
      text: 'Click here for Maricopa Small Business Development Center to see more upcoming events and trainers near you.',
      link: 'https://www.maricopa-sbdc.com/events/',
    },
  },
  california: {
    name: 'California',
    map: 'https://i.ibb.co/rkmGKh7/icons8-california-100.png',
    
    partners: [
      {
        name: 'Access, Inc',
        image: 'https://i.ibb.co/2ySwDj9/Access-Inc-California.png',
        website: 'https://www.access2jobs.org',
      },
      {
        name: 'Karen Organization of San Diego',
        image: 'https://i.ibb.co/SwLmJrL/Karen-org.png',
        website: 'https://karensandiego.org/',
      },
      {
        name: 'Union of Pan Asian Communities',
        image: 'https://i.ibb.co/5Gs2PTb/UPAC-logo-2x-1.png',
        website: 'https://www.upacsd.com/',
      },
      ],
    body: 'IRC CNPP will support the small business communities in San Diego County by providing information and tools to help stabilize and grow small businesses, including individualized counseling, mentoring, and training. Business advisors can also help small business owners apply for small business relief grants and loans and assist small business owners who have already received COVID-19 relief loans prepare documentation in support of loan forgiveness.  This includes current San Diego County and California Relief Grant programs. Project partners also offer industry-specific trainings for entrepreneurs interested in or currently operating childcare centers.  Interpretation services for all services and trainings are available upon request.',
    events: [                        
                      {
        title: 'Start-Up Essentials: From Concept to Creation',
        date: 'April 2',
        time: '4:00 PM- 8:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18298',
      },
                      {
        title: 'Creating a Sales Plan That Produces Long-term Results',
        date: 'April 3',
        time: '3:00 PM - 5:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18227',
      },
                       {
        title: 'Starting Your Business: A Step-by-Step Guide',
        date: 'April 4',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/17811',
      },
                             {
        title: 'Instagram and Tik Tok Strategy',
        date: 'April 8',
        time: '4:00 PM - 5:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18088',
      },
                          {
        title: 'How Successful Companies Use Social Media',
        date: 'April 9',
        time: '10:00 AM - 12:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18203',
      },
                           {
        title: 'Iniciando su Negocio de Camion de Comida',
        date: 'April 9',
        time: '3:00 PM - 5:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18393',
      },
                             {
        title: 'Starting Your Food Truck Business',
        date: 'April 9',
        time: '3:00 PM - 5:00 PM (PDT)',
        type: 'In Person - 1250 W Main St, El Centro CA 92243-2817',
        link: 'https://sdsbdc.ecenterdirect.com/events/18392',
      },
                          {
        title: 'Business Plans That Get Results',
        date: 'April 10',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18221',
      },
                            {
        title: 'Doing Business with Military Exchanges',
        date: 'April 10',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/17741',
      },
                            {
        title: 'Iniciando Tu Negocio de Comida Desde Casa',
        date: 'April 11',
        time: '3:00 PM - 5:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18391',
      },
                                 {
        title: 'Starting Your Homebased Food Business',
        date: 'April 11',
        time: '3:00 PM - 5:00 PM (PDT)',
        type: 'In Person - 1250 W Main St, El Centro CA 92243-2817',
        link: 'https://sdsbdc.ecenterdirect.com/events/18390',
      },
                                      {
        title: 'Connecting with Contracts',
        date: 'April 12',
        time: '8:30 AM - 12:00 PM (PDT)',
        type: 'In Person - MiraCosta College San Elijo Campus 3333 Manchester Avenue, Cardiff CA 92007',
        link: 'https://sdsbdc.ecenterdirect.com/events/17716',
      },
                                 {
        title: 'Branding with Purpose',
        date: 'April 16',
        time: '5:00 PM - 6:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18158',
      },
                                    {
        title: 'Use These 3 Stages Of “Awareness” To Get Customers & Clients Using Social Media',
        date: 'April 16',
        time: '10:00 AM - 12:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18208',
      },
                                      {
        title: 'Good Business- How To Include Charitable Giving Into Your Business',
        date: 'April 17',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/17979',
      },
                                         {
        title: 'New Hire Onboarding-What is the mandatory new hire paperwork?',
        date: 'April 17',
        time: '4:00 PM - 5:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18177',
      },
                                             {
        title: 'Cybersecurity – How to Better Prepare for DoD Cybersecurity Requirements',
        date: 'April 18',
        time: '1:00 PM - 3:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18233',
      },
                                                {
        title: 'Opening and Operating a Successful Retail Store',
        date: 'April 18',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/17790',
      },
                                                  {
        title: 'Pitch Perfect: Mastering the Arts of the Ask and Smart Fund Allocation.',
        date: 'April 18',
        time: '5:00 PM - 6:30 PM (PDT)',
        type: 'In Person - Sherman Heights Community Center 2258 Island Ave, San Diego CA 92102',
        link: 'https://sdsbdc.ecenterdirect.com/events/18492',
      },
                                                     {
        title: 'Build Customer Loyalty with Excellent Customer Service',
        date: 'April 19',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18230',
      },
                                                           {
        title: 'Estrategia de Redes Sociales',
        date: 'April 22',
        time: '6:00 PM - 7:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18149',
      },
                  {
        title: 'Grow with Google - Make Better Business Decisions with Analytics',
        date: 'April 23',
        time: '5:00 PM - 6:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18157',
      },
                  {
        title: 'How to Find Business Using LinkedIn',
        date: 'April 23',
        time: '10:00 AM - 12:00 PM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18214',
      },
                 {
        title: 'Business Plans That Get Results',
        date: 'April 24',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18222',
      },
              {
        title: 'Grow with Google – Get Your Local Business on Google Search & Maps',
        date: 'April 30',
        time: '9:00 AM - 10:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18156',
      },
              {
        title: 'Creating a Sales Plan That Produces Long-term Results',
        date: 'May 2',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/18228',
      },
               {
        title: 'Starting Your Business: A Step-by-Step Guide',
        date: 'May 2',
        time: '9:00 AM - 11:00 AM (PDT)',
        type: 'Online',
        link: 'https://sdsbdc.ecenterdirect.com/events/17812',
      },
    ],
    upcoming: {
      text: 'Click here for San Diego and Imperial Network Small Business Development Center to see more upcoming events and trainers near you.',
      link: 'https://sdsbdc.ecenterdirect.com/events?reset=1',
    },
  },
  georgia: {
    name: 'Georgia',
    map: 'https://i.ibb.co/KxzQw0q/icons8-georgia-100.png',
    partners: [
      {
        name: "Refugee Women's Network",
        image:
          'https://i.ibb.co/DQTpFjn/Refugee-Women-s-Network-Horizontal-GA.jpg',
        website: 'https://refugeewomensnetworkinc.org/',
      },
      {
        name: 'Somali American Community Center',
        image:
          'https://i.ibb.co/GJ7Wmzc/somali-american-community-center-GA-logo.png',
        website: 'https://www.facebook.com/somaliacc/',
      },
      {
        name: 'Latin American Association',
        image:
          'https://i.ibb.co/pJszmSF/Primary-Latin-American-Association-Vertical-RGB-Georgia.png',
        website: 'https://thelaa.org/',
      },
    ],
    body: 'IRC CNPP will support the small business communities in metro Atlanta and the surrounding areas by providing information and tools to help stabilize and grow local business, including individualized counseling, mentoring, and training. Business advisors can also help small business owners apply for small business relief grants and loans and assist small business owners who have already received COVID-19 relief loans prepare documentation in support of loan forgiveness.  This includes the current City of Atlanta Resurgence Grant.   Partners in this project also have business incubator programs for women and BIPOC entrepreneurs.  Interpretation services for all services and trainings are available upon request.',
    events: [
           {
        title: 'Myths & Realities of Small Business Funding',
        date: 'April 3',
        time: '9:00AM to 12:00PM',
        type: 'In Person - UGA SBDC Rome',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3317946#courseSectionDetails_3318039',
          },
        {
        title: 'From Risky to Resilient: Strategic Growth for Entrepreneurs',
        date: 'April 3',
        time: '9:00AM to 12:00PM',
        type: 'In Person - UGA SBDC Columbus',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3367422#courseSectionDetails_3367458',
          },
         {
        title: 'Finding the Financing Fit for Your Business',
        date: 'April 5',
        time: '10:00AM to 11:00AM',
        type: 'Online',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3313301#courseSectionDetails_3400064',
          },
          {
        title: 'Myths and Realities of Small Business Funding',
        date: 'April 8',
        time: '9:00 AM to 12:00PM',
        type: 'In Person - UGA SBDC Savannah and Statesboro',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3357137#courseSectionDetails_3357153',
          },
          {
        title: 'Harvesting Success: Guide to Ag Financing',
        date: 'April 10',
        time: '9:00AM to 11:30AM',
        type: 'In Person - UGA SBDC Macon',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3256077#courseSectionDetails_3257766',
          },
           {
        title: 'Harvesting Success: Guide to Ag Financing',
        date: 'April 11',
        time: '9:00AM to 11:30AM',
        type: 'In Person - UGA SBDC Albany',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3284611#courseSectionDetails_3286281',
          },
            {
        title: 'Harvesting Success: Guide to Ag Financing',
        date: 'April 15',
        time: '9:00AM to 11:30AM',
        type: 'In Person - UGA SBDC Rome',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3257120#courseSectionDetails_3257279',
          },
             {
        title: 'Myths and Realities of Small Business Funding',
        date: 'April 24',
        time: '9:00 AM to 12:00PM',
        type: 'In Person - UGA SBDC Savannah and Statesboro',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=3352164#courseSectionDetails_3352276',
          },
               {
        title: 'Digital Marketing Bootcamp',
        date: 'April 25',
        time: '9:00 AM to 12:00PM',
        type: 'In Person - UGA SBDC Augusta',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=2773569#courseSectionDetails_3343853',
          },
             {
        title: 'Myths and Realities of Small Business Funding',
        date: 'April 25',
        time: '2:00PM to 5:00PM',
        type: 'Online',
        link: 'https://training.georgiasbdc.org/search/publicCourseSearchDetails.do?method=load&courseId=2882663#courseSectionDetails_3248918',
          },
    ],
    upcoming: {
      text: 'Click here for Georgia Small Business Development Center-Minority Office to see a list of upcoming events and trainers in the network.',
      link: 'https://www.georgiasbdc.org/training/',
    },
  },
  iowa: {
    name: 'Iowa',
    map: 'https://i.ibb.co/nM3LZ0B/icons8-iowa-100.png',
    partners: [
      {
        name: 'Drake University',
        image: 'https://i.ibb.co/xzTnjJN/Drake-University-Logo-Iowa.png',
        website: 'https://www.drake.edu/businessclinic/',
      },
      {
        name: 'Iowa Center for Economic Success',
        image:
          'https://i.ibb.co/XsyWvfV/Iowa-Center-for-Economic-Success-Iowa.jpg',
        website: 'https://www.theiowacenter.org',
      },
      {
        name: 'Lutheran Services',
        image: 'https://i.ibb.co/5TDHfRN/Lutheran-Services-in-Iowa.png',
        website: 'https://lsiowa.org/refugee/community-navigator-program/',
      },
      {
        name: 'Iowa’s West Coast Initiative',
        image:
          'https://i.ibb.co/LvbnHGZ/City-of-Sioux-City-Iowa-s-West-Coast-Initiative-Logo-1.png',
        website: 'https://iawestcoast.com/',
      },
      {
        name: 'Siouxland Economic Development Corporation',
        image:
          'https://i.ibb.co/yYJyGh8/City-of-Sioux-City-Iowa-s-West-Coast-Initiative-Logo-2.png',
        website: 'https://iawestcoast.com/',
      },
    ],
    body: 'IRC CNPP will support the small business communities in Iowa by providing information and tools to help stabilize and grow your business, including individualized counseling, mentoring, and training. Business advisors can also help small business owners apply for small business relief grants and loans and assist small business owners who have already received COVID-19 relief loans prepare documentation in support of loan forgiveness. Partners in this project also have business accelerator programs, lending services, and expertise in scaling your agriculture business. Interpretation services for all services and trainings are available upon request.',
    events: [          
                   {
        title: 'Always Ready: Getting Ready',
        date: 'April 2',
        time: '12:00 pm - 1:00 pm CDT',
        type: 'In Person - 2210 Grand Ave, Des Moines, IA 50312',
        link: 'https://theiowacenter.org/event/always-ready-getting-ready-in-person-2/',
          },
                   {
        title: 'Always Ready: Lending',
        date: 'April 3',
        time: '2:00 pm - 1:00 pm CDT',
        type: 'In Person - 2210 Grand Ave, Des Moines, IA 50312',
        link: 'https://theiowacenter.org/event/always-ready-lending-in-person-3/',
          },
                               {
        title: 'ALWAYS READY: FINANCIALS',
        date: 'April 9',
        time: '3:00 pm - 4:00 pm CDT',
        type: 'Online',
        link: 'https://theiowacenter.org/event/always-ready-financials-36/',
          },
                                    {
        title: 'ALWAYS READY: CREDIT',
        date: 'April 10',
        time: '3:00 pm - 4:00 pm CDT',
        type: 'Online',
        link: 'https://theiowacenter.org/event/always-ready-credit-9/',
          },
                                       {
        title: 'ALWAYS READY: BUSINESS PLAN',
        date: 'April 16',
        time: '3:00 pm - 4:00 pm CDT',
        type: 'Online',
        link: 'https://theiowacenter.org/event/always-ready-business-plan-34/',
          },
                                   {
        title: 'ALWAYS READY: MARKETING (IN-PERSON)',
        date: 'April 17',
        time: '12:00 pm - 1:00 pm CDT',
        type: 'In Person - 2210 Grand Ave, Des Moines, IA 50312',
        link: 'https://theiowacenter.org/event/always-ready-marketing-in-person-3/',
          },
                                     {
        title: 'ALWAYS READY: Business Plan (IN-PERSON)',
        date: 'March 26',
        time: '3:00 pm - 4:00 pm CDT',
        type: 'In Person - 2210 Grand Ave, Des Moines, IA 50312',
        link: 'https://theiowacenter.org/event/always-ready-business-plan-in-person-3/',
          },
                                           {
        title: 'AARP: WORK FOR YOURSELF AT 50+',
        date: 'April 22',
        time: '9:00 am - 11:00 am CDT',
        type: 'Online',
        link: 'https://theiowacenter.org/event/aarp-work-for-yourself-at-50-9/',
          },
                                                 {
        title: 'MADE IN IOWA: HOQ',
        date: 'April 23',
        time: '9:00 am - 10:30 am CDT',
        type: 'In Person - HoQ Restaurant  303 E 5th St. Des Moines, IA 50309 ',
        link: 'https://theiowacenter.org/event/made-in-iowa-hoq/',
          },
                                                 {
        title: 'I NEED A PHYSICAL LOCATION FOR MY BUSINESS: HOW DO I GET STARTED?',
        date: 'April 29',
        time: '3:00 pm - 4:30 pm CDT',
        type: 'In Person - 2210 Grand Ave, Des Moines, IA 50312',
        link: 'https://theiowacenter.org/event/i-need-a-physical-location-for-my-business-how-do-i-get-started-2/',
          },
    ],
    upcoming: {
      text: 'Click here for Iowa Small Business Development Center to see more upcoming events and trainers near you.',
      link: 'https://theiowacenter.org/services/classes/',
    },
  },
  kansas: {
    name: 'Kansas',
    map: 'https://i.ibb.co/1qng885/icons8-kansas-100.png',
    partners: [],
    body: 'IRC CNPP will support the small business communities in Kansas by providing information and tools to help stabilize and grow local small businesses, including individualized counseling, mentoring, and training.  Business advisors can also help small business owners apply for small business relief grants and loans and assist small business owners who have already received COVID-19 relief loans prepare documentation in support of loan forgiveness.  Interpretation services for all services and trainings are available upon request.',
    events: [     
                             {
        title: 'Spring Clean Your Social Media',
        date: 'April 2',
        time: '12:00 pm (CDT)',
        type: 'Online',
        link: 'https://secure.touchnet.com/C21797_ustores/web/product_detail.jsp?PRODUCTID=5079&SINGLESTORE=true',
          },            
                            {
        title: 'Vital Topics in Business',
        date: 'April 4',
        time: '10:00 am (CDT)',
        type: 'In Person - Topeka-Shawnee County Public Library, 1515 SW 10th Ave Topeka, KS 66604',
        link: 'https://www.washburnsmallbusiness.com/workshops.html#calendar-b76765c6-32cd-41ab-a4fe-a8f97ec32c08-event-lt8zazny',
          },   
      {
        title: 'Start Up and Start Right',
        date: 'April 10',
        time: '12:00 pm (CDT)',
        type: 'Online',
        link: 'https://secure.touchnet.com/C21797_ustores/web/product_detail.jsp?PRODUCTID=5037&SINGLESTORE=true',
          },
                           {
        title: 'Non-Profit 101',
        date: 'April 11',
        time: '7:00 pm (CDT)',
        type: 'In Person - Washburn University School of Law 2073 SW Washburn Terrace E Topeka, KS 6662',
        link: 'https://www.washburnsmallbusiness.com/workshops.html#calendar-b76765c6-32cd-41ab-a4fe-a8f97ec32c08-event-lt8zazny',
          },   
         {
        title: 'Lunch & Learn - Patent Searching Techniques',
        date: 'April 12',
        time: '12:00 pm (CDT)',
        type: 'Online',
        link: 'https://secure.touchnet.com/C21797_ustores/web/product_detail.jsp?PRODUCTID=4956&SINGLESTORE=true',
          },
        {
        title: 'Manage Your Own Social Media',
        date: 'April 16',
        time: '12:00 pm (CDT)',
        type: 'Online',
        link: 'https://secure.touchnet.com/C21797_ustores/web/product_detail.jsp?PRODUCTID=5063&SINGLESTORE=true',
          },
                           {
        title: 'How To Start A Business',
        date: 'April 17',
        time: '6:30 pm (CDT)',
        type: 'In Person - Topeka-Shawnee County Public Library1515 SW 10th Ave Topeka, KS 66604',
        link: 'https://www.washburnsmallbusiness.com/workshops.html#calendar-b76765c6-32cd-41ab-a4fe-a8f97ec32c08-event-lt8zazny',
          },   
              {
        title: 'Unleash the Power of Your Credit',
        date: 'April 18',
        time: '10:00 am (CDT)',
        type: 'Online',
        link: 'https://secure.touchnet.com/C21797_ustores/web/product_detail.jsp?PRODUCTID=5064&SINGLESTORE=true',
          },
                                 {
        title: 'Small Business, Big Protection',
        date: 'April 18',
        time: '7:00 pm (CDT)',
        type: 'In Person - Washburn University School of Law 2073 SW Washburn Terrace E Topeka, KS 6662',
        link: 'https://www.washburnsmallbusiness.com/workshops.html#calendar-b76765c6-32cd-41ab-a4fe-a8f97ec32c08-event-lt8zazny',
          },   
          {
        title: 'Accounting For Non-accountants',
        date: 'April 30',
        time: '12:00 pm (CDT)',
        type: 'Online',
        link: 'https://secure.touchnet.com/C21797_ustores/web/product_detail.jsp?PRODUCTID=5087&SINGLESTORE=true',
          },
    ],
    upcoming: {
      text: 'Click here for Kansas Small Business Development Center to see more upcoming events and trainers near you.',
      link: 'https://www.kansassbdc.net/training',
    },
  },
  utah: {
    name: 'Utah',
    map: 'https://i.ibb.co/ck954WH/icons8-utah-100.png',
    partners: [
      {
        name: 'Asian Association of Utah',
        image:
          'https://i.ibb.co/t42925r/Asian-Association-of-Utah-Logo-Utah.png',
        website: 'http://aau-slc.org/',
      },
      {
        name: 'Holy Cross Ministries',
        image: 'https://i.ibb.co/m6fxrDM/Holy-Cross-Ministries-Utah.png',
        website: 'https://www.hcmutah.org',
      },
      {
        name: 'Cache Refugee and Immigrant Connection',
        image:
          'https://i.ibb.co/qrSH0yL/Cache-Refugee-and-Immigrant-Connection-Utah.png',
        website: 'https://www.cacherefugees.org ',
      },
      {
        name: 'GK Folks Foundation',
        image: 'https://i.ibb.co/g7cPML6/GK-Folks-Foundation-Utah.png',
        website: 'https://www.gkfolksfoundation.org/',
      },
    ],
    body: 'IRC CNPP will support the small business communities the Salt Lake City metro region and the surrounding areas by providing information and tools to help stabilize and grow your business, including individualized counseling, mentoring, and training. Business advisors can also help small business owners apply for small business relief grants and loans and assist small business owners who have already received COVID-19 relief loans prepare documentation in support of loan forgiveness.  Interpretation services are available upon request. Partners in this project also have business incubator programs for food entrepreneurs.  Interpretation services for all services and trainings are available upon request.',
    events: [      
             {
        title: 'Wordpress Workshop',
        date: 'April 2',
        time: '2:00 pM to 3:30 PM MT',
        type: 'Online',
        link: 'https://clients.utahsbdc.org/reg.aspx?mode=event&event=6440026',
          }, 
                  {
        title: 'Taxes and Small Business',
        date: 'April 9',
        time: '11:30 AM to 12:30 PM MT',
        type: 'In Person - Small Business Development Center Davis Technical College',
        link: 'https://clients.utahsbdc.org/reg.aspx?mode=event&event=27440009',
          }, 
       {
        title: 'Business Essentials',
        date: 'April 11',
        time: '6:00 PM to 8:00 PM MT',
        type: 'Online',
        link: 'https://clients.utahsbdc.org/reg.aspx?mode=event&event=6440028',
          }, 
               {
        title: 'Effective Sales Techniques',
        date: 'April 17',
        time: '9:00 AM to 12:00 PM MT',
        type: 'In Person - Small Business Development Center Davis Technical College',
        link: 'https://clients.utahsbdc.org/reg.aspx?mode=event&event=27440003',
          }, 
                    {
        title: 'How to Start a Business 101',
        date: 'April 18',
        time: '6:00 PM to 8:00 PM  MT',
        type: 'In Person - Orem/Provo SBDC Utah Valley University',
        link: 'https://clients.utahsbdc.org/reg.aspx?mode=event&event=6440031',
          },
        {
        title: 'Starting Your Business 101',
        date: 'April 23',
        time: '3:00 PM to 4:30 PM MT',
        type: 'Online',
        link: 'https://clients.utahsbdc.org/workshop.aspx?ekey=4440013',
          }, 
         {
        title: 'Facebook/Instagram Ads: Create and Manage Ads like a Pro!',
        date: 'April 24',
        time: '6:00 PM to 7:00 PM MT',
        type: 'Online',
        link: 'https://clients.utahsbdc.org/reg.aspx?mode=event&event=6440032',
          }, 
       {
        title: 'A.I. for Marketing - Demystified with Matt Sheehan - Online',
        date: 'April 30',
        time: '9:00 AM to 10:30 AM MT',
        type: 'Online',
        link: 'https://clients.utahsbdc.org/workshop.aspx?ekey=4440019',
          }, 
    ],
    upcoming: {
      text: 'Click here for Utah’s Small Business Development Center to see more upcoming events and trainers near you.',
      link: 'https://clients.utahsbdc.org/events.aspx',
    },
  },
  // This is where you can add additional regions or states
  /*
  kansas: {
    name: 'Region Name',
    map: 'https://example.com/image.jpg',
    partners: [
      {
        name: 'Partner Name',
        image: 'https://example.com/image.jpg',
        website: 'https://example.com/',
      },
    ],
    body: 'This is the text appearing at the top of the page',
    events: [
      {
        title: 'Event title',
        language: 'Event language',
        date: 'Event date',
        time: 'Event time',
        type: 'Event type',
        address: 'Event location address',
        link: 'https://example.com/',
      },
    ],
    upcoming: {
      text: 'This is the text for upcoming events',
      link: 'https://example.com',
    },
  },
  */
}
