name: Deploy to GitHub Pages


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      NEXT_PUBLIC_BASE_PATH: /cnpp-website

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - name: Get files
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Build project and export files
        run: npm run build
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: app/out
